### PR TITLE
Vikram/sd3.5m skiplayercfg

### PR DESCRIPTION
**Pull request by voletiv**
Adds SkipLayerCFGDenoiser for SD3.5-Medium

### CODE REVIEW

**Comment by CodeExplode** [comment]
Heya, just wondering what layers it is recommended to use this on, for which noise ranges?

**Comment by stduhpf** [comment]
Can someone help me understand what is the point of those changes? How does this affect output, speed and all?

**Comment by Dango233** [comment]
SLG is for enhancing the guidance vector of a "certain part" of the model - in this case, we regard it as a way to enhance structural information like hands and anatomy,

It requires an additional forward pass to work so will slowdown the generation by around 33%

**Comment by CodeExplode** [comment]
Dango233 do you know if this idea is unique to this model? Or has it been tried on 3.5 large, SDXL, SD1.5, etc?

**Pull request merged**
